services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app:delegated
      - ./backend/analyzer.db:/app/analyzer.db
    environment:
      - FLASK_ENV=development
    dns:
      - 8.8.8.8
      - 1.1.1.1
    env_file:
      - ./backend/.env
    restart: unless-stopped

